# -*- coding: utf-8 -*-
# SPDX-FileCopyrightText: : Sangeeta Mohanty, Yu-Chi Chang
# SPDX-License-Identifier: MIT
# coding: utf-8

layout:
  page_title: Germany-grid-line-viz
  chart_title: Grid Lines of Germany
