name: germany-grid-line-viz
channels:
  - conda-forge
dependencies:
  - python >=3.11,<3.12.0a0
  - plotly==5.19
  - pip==24.0
  - pandas==2.1 # >=1.4.3
  - geopandas>=0.11.1
  - yaml
  # Keep in conda environment when calling ipython
  - ipython
  - ipykernel==6.25.0
  - pip:
      - streamlit==1.33.0
      - PyYAML==6.0.1
